"""Stamp out many regional scout agents from a few templates — this is how the
roster scales toward 200 without hand-writing each one. It writes
`roster.generated.yaml`, which the runner merges with `roster.yaml` automatically.

    python tools/expand_roster.py           # generate (prints the count)
    python tools/expand_roster.py --clear    # delete the generated file

Add towns or roles below to grow the roster. Remember: more agents just means a
longer rotation — throughput is still capped by `daily_call_budget` in config.yaml,
so this never blows your free quotas.
"""
from __future__ import annotations
import pathlib
import re
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "roster.generated.yaml"

# Vogelsbergkreis + Fulda-Umland — extend freely.
TOWNS = [
    "Lauterbach", "Alsfeld", "Schotten", "Herbstein", "Grebenhain", "Homberg (Ohm)",
    "Kirtorf", "Muecke", "Romrod", "Feldatal", "Gemuenden (Felda)", "Freiensteinau",
    "Ulrichstein", "Schwalmtal", "Wartenberg", "Antrifttal", "Grebenau", "Lautertal",
    "Fulda", "Petersberg", "Kuenzell", "Neuhof", "Huenfeld", "Grossenlueder",
    "Eichenzell", "Hosenfeld", "Flieden", "Tann", "Gersfeld", "Hilders",
]

# Each role becomes one agent per town. Add roles to multiply the roster.
ROLES = [
    {
        "suffix": "chancen", "name": "Chancen-Scout", "department": "Chancen",
        "interval": 1440,
        "system": ("Du bist ein geerdeter Business-Chancen-Scout fuer Osthessen. "
                   "Konkret, lokal, keine Luftschloesser."),
        "task": ("Nenne EINE konkrete, schlank startbare Geschaefts-Chance speziell "
                 "fuer {town}. Format: WAS / WARUM HIER / ERSTER SCHRITT. Je 1 Satz."),
    },
    {
        "suffix": "handwerk", "name": "Handwerk-Sichtbarkeit", "department": "Chancen",
        "interval": 1440,
        "system": ("Du hilfst lokalen Handwerksbetrieben, online gefunden zu werden. "
                   "Praktisch und ehrlich."),
        "task": ("Nenne 1 konkreten Betriebstyp in {town}, der von einem "
                 "Digital-Sichtbarkeits-Paket profitieren wuerde, plus 1 Satz "
                 "Ansprache-Idee."),
    },
    {
        "suffix": "direkt", "name": "Direktvermarktung", "department": "Chancen",
        "interval": 2880,
        "system": ("Du kennst regionale Direktvermarktung (Hofprodukte, Abo-Boxen). "
                   "Bodenstaendig."),
        "task": ("Skizziere 1 Direktvermarktungs-Idee fuer {town} oder Umgebung: "
                 "WAS / fuer WEN / ERSTER SCHRITT. Je 1 Satz."),
    },
    {
        "suffix": "tourismus", "name": "Vulkanregion-Tourismus", "department": "Chancen",
        "interval": 2880,
        "system": ("Du entwickelst kleine, online-buchbare Erlebnisangebote fuer die "
                   "Vulkanregion Vogelsberg/Rhoen."),
        "task": ("Nenne 1 buchbares Erlebnis-Paket rund um {town}: WAS / fuer WEN / "
                 "ERSTER SCHRITT. Je 1 Satz."),
    },
    {
        "suffix": "senioren", "name": "Senioren-Alltagsdienste", "department": "Kunden",
        "interval": 2880,
        "system": ("Du entwickelst wuerdevolle Alltagshilfen fuer aeltere Menschen in "
                   "verstreuten Doerfern. Respektvoll, realistisch."),
        "task": ("Nenne 1 Alltags-Dienst fuer Senioren in {town}: WAS / WARUM HIER / "
                 "ERSTER SCHRITT. Je 1 Satz."),
    },
]


def slug(text: str) -> str:
    text = text.lower()
    text = (text.replace("ae", "ae").replace("oe", "oe").replace("ue", "ue"))
    return re.sub(r"[^a-z0-9]+", "-", text).strip("-")


def build():
    agents = []
    for town in TOWNS:
        for role in ROLES:
            agents.append({
                "id": f"{role['suffix']}-{slug(town)}",
                "name": f"{role['name']} — {town}",
                "department": role["department"],
                "interval_minutes": role["interval"],
                "system": role["system"],
                "task": role["task"].format(town=town),
            })
    return agents


def main():
    if "--clear" in sys.argv:
        if OUT.exists():
            OUT.unlink()
            print(f"removed {OUT.name}")
        else:
            print("nothing to clear")
        return
    agents = build()
    header = ("# AUTO-GENERATED by tools/expand_roster.py — edit that script, not this.\n"
              "# Merged with roster.yaml at runtime.\n")
    OUT.write_text(header + yaml.safe_dump({"agents": agents}, allow_unicode=True,
                                           sort_keys=False), encoding="utf-8")
    print(f"wrote {OUT.name}: {len(agents)} agents "
          f"({len(TOWNS)} towns x {len(ROLES)} roles)")


if __name__ == "__main__":
    main()
